// packages/draw-svelte/src/lib/components/Toolbar.svelte
<script lang="ts">
  import { onDestroy, onMount, type Snippet } from "svelte";
  import { PENS } from "../engine/pens.js";
  import type { Pen, PenId, ToolId } from "../engine/types.js";
  import { resolveSwatches } from "../palette.js";
  import { TooltipController } from "../state/tooltip.svelte.js";
  import BarSlider from "./BarSlider.svelte";
  import HexField from "./HexField.svelte";
  import Icon from "./Icon.svelte";
  import MorphBar from "./MorphBar.svelte";
  import ToolIcon, { type Look } from "./ToolIcon.svelte";
  import ToolMenu from "./ToolMenu.svelte";
  import TooltipLayer from "./TooltipLayer.svelte";
  import css from "./Toolbar.module.css";
  import morph from "./MorphBar.module.css";

  export type ToolState = {
    active: ToolId;
    color: string;
    size: number;
    opacity: number;
    eraserSize: number;
  };

  export type TooltipOptions = {
    scope?: "all" | "tools";
    delay?: number;
    style?: string;
  };

  export type ToolbarProps = {
    tool: ToolState;
    inkFor: (id: PenId) => string;
    tooltips?: boolean | TooltipOptions;
    pens?: Pen[];
    eraser?: boolean;
    controls?: {
      color?: boolean;
      size?: boolean;
      opacity?: boolean;
      undo?: boolean;
      clear?: boolean;
      custom?: boolean;
      minimize?: boolean;
    };
    settings?: "bar" | "tool";
    theme?: "light" | "dark" | "auto";
    look?: Look;
    gauge?: boolean;
    shortcuts?: boolean;
    swatches?: string[];
    onSelect: (id: ToolId) => void;
    onChange: (patch: Partial<ToolState>) => void;
    canUndo: boolean;
    canRedo: boolean;
    onUndo: () => void;
    onRedo: () => void;
    onClear: () => void;
    hasStrokes: boolean;
    placement?: "bottom" | "left" | "right";
    collapsed?: boolean;
    onCollapse?: () => void;
    onExpand?: () => void;
    shift?: number;
    /** Custom content for the minimized disc. */
    icon?: Snippet;
    onMeasure?: (width: number, height: number) => void;
  };

  let {
    tool,
    inkFor,
    tooltips = true,
    pens = PENS,
    eraser = true,
    controls,
    settings = "bar",
    theme = "light",
    look = "classic",
    gauge = false,
    shortcuts = true,
    swatches,
    onSelect,
    onChange,
    canUndo,
    canRedo,
    onUndo,
    onRedo,
    onClear,
    hasStrokes,
    placement = "bottom",
    collapsed = false,
    onCollapse,
    onExpand,
    shift = 0,
    icon,
    onMeasure,
  }: ToolbarProps = $props();

  type Mode = "tools" | "ink" | "brush" | "spectrum";
  let mode = $state<Mode>("tools");
  let canPick = $state(false);
  let openTool = $state<HTMLElement | null>(null);
  let closingTool = $state(false);
  let frozen = $state<{
    size: number;
    maxSize: number;
    opacity: number;
    color: string;
    showOpacity: boolean;
  } | null>(null);
  let closeTimer: ReturnType<typeof setTimeout> | null = null;
  const tooltipController = new TooltipController(
    () => tooltips,
    () => placement,
  );
  const tooltip = tooltipController.tooltip;

  const isEraser = $derived(tool.active === "eraser");
  const vertical = $derived(placement !== "bottom");
  const size = $derived(isEraser ? tool.eraserSize : tool.size);
  const maxSize = $derived(isEraser ? 120 : 80);
  const live = $derived({
    size,
    maxSize,
    opacity: tool.opacity,
    color: isEraser ? "#c9c7c2" : tool.color,
    showOpacity: !isEraser,
  });
  const menu = $derived(frozen ?? live);
  const show = $derived({
    color: controls?.color ?? true,
    size: controls?.size ?? true,
    opacity: controls?.opacity ?? true,
    custom: controls?.custom ?? true,
    undo: controls?.undo ?? true,
    clear: controls?.clear ?? true,
    minimize: controls?.minimize ?? true,
  });
  const sizeLabel = $derived(
    show.size && show.opacity && !isEraser
      ? "Size & opacity"
      : show.size
        ? "Size"
        : "Opacity",
  );
  onMount(() => {
    canPick = "EyeDropper" in window;
  });
  onDestroy(() => {
    if (closeTimer) clearTimeout(closeTimer);
    tooltipController.destroy();
  });

  function closeMenu() {
    if (closeTimer) clearTimeout(closeTimer);
    frozen = live;
    closingTool = true;
    closeTimer = setTimeout(() => {
      openTool = null;
      closingTool = false;
      frozen = null;
    }, 150);
  }

  function showMenu(element: HTMLElement) {
    if (closeTimer) clearTimeout(closeTimer);
    frozen = null;
    closingTool = false;
    openTool = element;
  }

  function isLight(hex: string) {
    const match = /^#?([\da-f]{6})$/i.exec(hex.trim());
    if (!match) return false;
    const value = parseInt(match[1], 16);
    return (
      (0.299 * ((value >> 16) & 255) +
        0.587 * ((value >> 8) & 255) +
        0.114 * (value & 255)) /
        255 >
      0.62
    );
  }

  type Picker = new () => {
    open(options?: {
      signal?: AbortSignal;
    }): Promise<{ sRGBHex: string }>;
  };
  let picking = false;
  async function pickFromScreen() {
    if (picking) return null;
    const EyeDropper = (window as unknown as { EyeDropper?: Picker })
      .EyeDropper;
    if (!EyeDropper) return null;
    picking = true;
    const abort = new AbortController();
    const cancel = () => abort.abort();
    window.addEventListener("blur", cancel, { once: true });
    document.addEventListener("visibilitychange", cancel, { once: true });
    try {
      return (await new EyeDropper().open({ signal: abort.signal })).sRGBHex;
    } catch {
      return null;
    } finally {
      picking = false;
      window.removeEventListener("blur", cancel);
      document.removeEventListener("visibilitychange", cancel);
    }
  }

</script>

{#snippet back()}
  <button
    type="button"
    class={css.round}
    onclick={() => {
      mode = "tools";
    }}
    aria-label="Back to tools"
    use:tooltip={{ label: "Back", control: true }}
  >
    <Icon name="back" />
  </button>
{/snippet}

{#snippet toolsPanel()}
  {#if show.undo}
    <span class={css.seated}>
      <button
        type="button"
        class={css.round}
        disabled={!canUndo}
        onclick={onUndo}
        aria-label="Undo"
        use:tooltip={{
          label: "Undo",
          hint: shortcuts ? "⌘Z" : undefined,
          control: true,
        }}
      >
        <Icon name="undo" />
      </button>
    </span>
    <span class={css.seated}>
      <button
        type="button"
        class={css.round}
        disabled={!canRedo}
        onclick={onRedo}
        aria-label="Redo"
        use:tooltip={{
          label: "Redo",
          hint: shortcuts ? "⇧⌘Z" : undefined,
          control: true,
        }}
      >
        <Icon name="redo" />
      </button>
    </span>
  {/if}

  {#if show.clear}
    <span class={css.seated}>
      <button
        type="button"
        class={css.round}
        data-tone="danger"
        disabled={!hasStrokes}
        onclick={onClear}
        aria-label="Clear"
        use:tooltip={{ label: "Clear all", control: true }}
      >
        <Icon name="trash" />
      </button>
    </span>
  {/if}

  {#if show.undo || show.clear}<span class={css.divider}></span>{/if}

  {#each pens as pen (pen.id)}
    <button
      type="button"
      class={css.tool}
      data-active={tool.active === pen.id || undefined}
      onclick={(event) => {
        if (settings === "tool" && tool.active === pen.id) {
          if (openTool && !closingTool) closeMenu();
          else showMenu(event.currentTarget);
          return;
        }
        if (openTool) closeMenu();
        onSelect(pen.id);
      }}
      aria-label={pen.name}
      aria-pressed={tool.active === pen.id}
      aria-expanded={settings === "tool" && tool.active === pen.id
        ? openTool !== null
        : undefined}
      use:tooltip={{
        label: pen.name,
        hint: shortcuts ? pen.key : undefined,
      }}
    >
      <ToolIcon
        id={pen.id}
        color={inkFor(pen.id)}
        {look}
        badge={gauge && tool.active === pen.id ? size : undefined}
      />
    </button>
  {/each}

  {#if eraser}
    <button
      type="button"
      class={css.tool}
      data-active={isEraser || undefined}
      onclick={() => onSelect("eraser")}
      aria-label="Eraser"
      aria-pressed={isEraser}
      use:tooltip={{
        label: "Eraser",
        hint: shortcuts ? "E" : undefined,
      }}
    >
      <ToolIcon id="eraser" color={tool.color} {look} />
    </button>
  {/if}

  {#if (show.size && settings === "bar") || show.color}
    <span class={css.divider}></span>
  {/if}

  {#if (show.size || show.opacity) && settings === "bar"}
    <span class={css.seated}>
      <button
        type="button"
        class={css.round}
        onclick={() => {
          mode = "brush";
        }}
        aria-label={sizeLabel}
        use:tooltip={{ label: sizeLabel, control: true }}
      >
        <span
          class={css.brushDot}
          style:width={`${6 + (size / maxSize) * 16}px`}
          style:height={`${6 + (size / maxSize) * 16}px`}
          style:background={isEraser ? "#c9c7c2" : tool.color}
          style:opacity={isEraser ? 1 : tool.opacity}
        ></span>
      </button>
    </span>
  {/if}

  {#if show.color}
    <span class={css.seated}>
      <button
        type="button"
        class={css.round}
        onclick={() => {
          mode = "ink";
        }}
        aria-label={`Ink colour — ${tool.color}`}
        use:tooltip={{ label: "Colour", control: true }}
      >
        <span class={css.wheel}>
          <span
            class={css.wheelInk}
            style:background={tool.color}
          ></span>
        </span>
      </button>
    </span>
  {/if}

  {#if show.minimize}<span class={css.divider}></span>{/if}
  {#if show.minimize}
    <span class={css.seated}>
      <button
        type="button"
        class={css.round}
        onclick={onCollapse}
        aria-label="Hide tools"
        use:tooltip={{ label: "Hide tools", control: true }}
      >
        <Icon name="collapse" />
      </button>
    </span>
  {/if}
{/snippet}

{#snippet inkPanel()}
  <div
    class={`${morph.centered} ${css.row} ${css.inkRow}`}
    data-open-end={!show.custom || undefined}
  >
    {@render back()}
    <span class={css.divider}></span>
    <div class={css.swatches}>
      {#each resolveSwatches(swatches, vertical) as color (color)}
        <button
          type="button"
          class={css.chip}
          data-active={tool.color.toLowerCase() === color.toLowerCase() ||
            undefined}
          style:background={color}
          onclick={() => {
            onChange({ color });
            if (isEraser) onSelect("pen");
          }}
          aria-label={color}
          title={color}
        >
          <svg
            class={css.tick}
            viewBox="0 0 16 16"
            fill="none"
            stroke={isLight(color) ? "#111" : "#fff"}
            stroke-width="2.4"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path d="M3.6 8.4 6.7 11.5 12.4 5.2" />
          </svg>
        </button>
      {/each}
    </div>
    {#if show.custom}
      <span class={css.divider}></span>
      <button
        type="button"
        class={css.custom}
        onclick={() => {
          mode = "spectrum";
        }}
        aria-label="Pick any colour"
        use:tooltip={{ label: "Any colour", control: true }}
      >
        <span></span>
      </button>
    {/if}
  </div>
{/snippet}

{#snippet spectrumPanel()}
  <div class={`${morph.centered} ${css.row}`}>
    <button
      type="button"
      class={css.round}
      onclick={() => {
        mode = "ink";
      }}
      aria-label="Back to swatches"
      use:tooltip={{ label: "Back", control: true }}
    >
      <Icon name="back" />
    </button>
    <span class={css.divider}></span>
    <span
      class={css.preview}
      style:background={tool.color}
      aria-hidden="true"
    ></span>
    {#if !vertical}
      <HexField
        value={tool.color}
        onChange={(color) => {
          onChange({ color });
          if (isEraser) onSelect("pen");
        }}
      />
    {/if}
    {#if canPick}
      <button
        type="button"
        class={css.round}
        aria-label="Pick a colour from the screen"
        use:tooltip={{ label: "Pick from screen", control: true }}
        onclick={async () => {
          const picked = await pickFromScreen();
          if (!picked) return;
          onChange({ color: picked });
          if (isEraser) onSelect("pen");
        }}
      >
        <Icon name="dropper" />
      </button>
    {/if}
  </div>
{/snippet}

{#snippet brushPanel()}
  <div class={`${morph.centered} ${css.row} ${css.tail}`}>
    {@render back()}
    {#if show.size}
      <span class={css.divider}></span>
      <BarSlider
        {vertical}
        label="Size"
        value={size}
        min={1}
        max={maxSize}
        curve={2}
        display={String(Math.round(size))}
        color={isEraser ? "#c9c7c2" : tool.color}
        onChange={(value) =>
          onChange(isEraser ? { eraserSize: value } : { size: value })}
      />
    {/if}
    {#if show.opacity && !isEraser}
      <span class={css.divider}></span>
      <BarSlider
        {vertical}
        label="Opacity"
        value={tool.opacity}
        min={0.05}
        max={1}
        display={`${Math.round(tool.opacity * 100)}%`}
        color={tool.color}
        checker
        onChange={(opacity) => onChange({ opacity })}
      />
    {/if}
  </div>
{/snippet}

{#snippet collapsedContent()}
  <span class={css.peek}>
    {#if icon}
      {@render icon()}
    {:else}
      <ToolIcon
        id={tool.active === "eraser" ? "eraser" : tool.active}
        color={tool.color}
        {look}
        size={42}
      />
    {/if}
  </span>
{/snippet}

<MorphBar
  active={mode}
  class={placement === "bottom"
    ? undefined
    : `${css.vertical} ${placement === "left" ? css.left : css.right}`}
  {vertical}
  side={placement === "bottom" ? undefined : placement}
  {collapsed}
  {onExpand}
  {shift}
  {onMeasure}
  {collapsedContent}
  panels={[
    { id: "tools", content: toolsPanel },
    { id: "ink", content: inkPanel },
    { id: "spectrum", content: spectrumPanel },
    { id: "brush", content: brushPanel },
  ]}
/>

<TooltipLayer controller={tooltipController} />

{#if settings === "tool" && openTool}
  <ToolMenu
    anchor={openTool}
    size={menu.size}
    maxSize={menu.maxSize}
    opacity={menu.opacity}
    color={menu.color}
    showOpacity={menu.showOpacity}
    {theme}
    closing={closingTool}
    onSize={(value) =>
      onChange(isEraser ? { eraserSize: value } : { size: value })}
    onOpacity={(opacity) => onChange({ opacity })}
    onClose={closeMenu}
  />
{/if}

// packages/draw/src/components/Toolbar.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { PENS } from "../engine/pens";
import type { Pen, PenId, ToolId } from "../engine/types";
import { resolveSwatches } from "../palette";
import { MorphBar } from "./MorphBar";
import { BarSlider } from "./BarSlider";
import {
  BackIcon,
  CollapseIcon,
  DropperIcon,
  RedoIcon,
  UndoIcon,
} from "./icons";
import { HexField, pickFromScreen, supportsEyeDropper } from "./HexField";
import { ToolIcon } from "./ToolIcon";
import { ToolMenu } from "./ToolMenu";
import { useTooltips, type TooltipOptions } from "./Tooltip";
import { TrashIcon } from "./TrashIcon";
import css from "./Toolbar.module.css";
import morph from "./MorphBar.module.css";

export type ToolState = {
  active: ToolId;
  color: string;
  size: number;
  opacity: number;
  eraserSize: number;
};

type Mode = "tools" | "ink" | "brush" | "spectrum";

/** Rough perceptual lightness, to pick a legible tick colour on a swatch. */
function isLight(hex: string) {
  const m = /^#?([\da-f]{6})$/i.exec(hex.trim());
  if (!m) return false;
  const n = parseInt(m[1], 16);
  return (
    (0.299 * ((n >> 16) & 255) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255)) /
      255 >
    0.62
  );
}

/** Everything lives in this one bar. */
export function Toolbar({
  tool,
  inkFor,
  tooltips = true,
  pens = PENS,
  eraser = true,
  controls,
  settings = "bar",
  theme,
  look = "classic",
  gauge = false,
  shortcuts = true,
  swatches,
  onSelect,
  onChange,
  canUndo,
  canRedo,
  onUndo,
  onRedo,
  onClear,
  hasStrokes,
  placement = "bottom",
  collapsed = false,
  onCollapse,
  onExpand,
  shift = 0,
  onMeasure,
  icon,
}: {
  tool: ToolState;
  /** The ink a given pen will draw with, so the tray can show it. */
  inkFor: (id: PenId) => string;
  /** Hover labels: `false` for none, or an object to narrow or restyle them. */
  tooltips?: boolean | TooltipOptions;
  /** The pens to offer, in tray order. */
  pens?: Pen[];
  /** Whether the eraser is offered. */
  eraser?: boolean;
  /** Where size and opacity live. */
  settings?: "bar" | "tool";
  theme?: "light" | "dark" | "auto";
  /** How the tools are drawn. */
  look?: "classic" | "studio";
  /** Print the current size on the barrel of the pen in hand. */
  gauge?: boolean;
  /** Whether to advertise keyboard shortcuts in the labels. */
  shortcuts?: boolean;
  /** The colours to offer, in place of the built-in palette. */
  swatches?: string[];
  /** Which built-in controls to show. */
  controls?: {
    color?: boolean;
    size?: boolean;
    opacity?: boolean;
    undo?: boolean;
    clear?: boolean;
    custom?: boolean;
    minimize?: boolean;
  };
  onSelect: (id: ToolId) => void;
  onChange: (patch: Partial<ToolState>) => void;
  canUndo: boolean;
  canRedo: boolean;
  onUndo: () => void;
  onRedo: () => void;
  onClear: () => void;
  hasStrokes: boolean;
  placement?: "bottom" | "left" | "right";
  collapsed?: boolean;
  onCollapse?: () => void;
  onExpand?: () => void;
  shift?: number;
  onMeasure?: (w: number, h: number) => void;
  /** Shown in the disc while minimised — the tool you're holding. */
  icon?: React.ReactNode;
}) {
  const [mode, setMode] = useState<Mode>("tools");
  /** Whether the screen can be sampled — settled after mount. */
  const [canPick, setCanPick] = useState(false);
  useEffect(() => setCanPick(supportsEyeDropper()), []);
  const isEraser = tool.active === "eraser";
  const vertical = placement !== "bottom";
  const size = isEraser ? tool.eraserSize : tool.size;
  const maxSize = isEraser ? 120 : 80;
  const tip = useTooltips(tooltips, placement);
  /** The tool whose settings are open, if any. */
  const [openTool, setOpenTool] = useState<HTMLElement | null>(null);
  /** Kept mounted while the menu plays its way out. */
  const [closingTool, setClosingTool] = useState(false);
  const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  /** What the menu was showing when it started to leave. */
  const live = {
    size,
    maxSize,
    opacity: tool.opacity,
    color: isEraser ? "#c9c7c2" : tool.color,
    // An eraser takes away; there is nothing to be partly opaque about.
    showOpacity: !isEraser,
  };
  const latest = useRef(live);
  latest.current = live;
  const [frozen, setFrozen] = useState<typeof live | null>(null);
  const menu = frozen ?? live;

  const closeMenu = useCallback(() => {
    if (closeTimer.current) clearTimeout(closeTimer.current);
    setFrozen(latest.current);
    setClosingTool(true);
    closeTimer.current = setTimeout(() => {
      setOpenTool(null);
      setClosingTool(false);
      setFrozen(null);
    }, 150);
  }, []);

  const showMenu = useCallback((el: HTMLElement) => {
    if (closeTimer.current) clearTimeout(closeTimer.current);
    setFrozen(null);
    setClosingTool(false);
    setOpenTool(el);
  }, []);

  useEffect(
    () => () => {
      if (closeTimer.current) clearTimeout(closeTimer.current);
    },
    [],
  );
  const show = {
    color: controls?.color ?? true,
    size: controls?.size ?? true,
    opacity: controls?.opacity ?? true,
    custom: controls?.custom ?? true,
    undo: controls?.undo ?? true,
    clear: controls?.clear ?? true,
    minimize: controls?.minimize ?? true,
  };

  /* What the size control is called, given what it actually opens. */
  const sizeLabel =
    show.size && show.opacity && !isEraser
      ? "Size & opacity"
      : show.size
        ? "Size"
        : "Opacity";

  const back = (
    <button
      type="button"
      className={css.round}
      onClick={() => setMode("tools")}
      aria-label="Back to tools"
      {...tip.bindControl("Back")}
    >
      <BackIcon />
    </button>
  );

  return (
    <>
      <MorphBar
        active={mode}
        className={
          placement === "bottom"
            ? undefined
            : `${css.vertical} ${placement === "left" ? css.left : css.right}`
        }
        vertical={placement !== "bottom"}
        side={placement === "bottom" ? undefined : placement}
        collapsed={collapsed}
        onExpand={onExpand}
        shift={shift}
        onMeasure={onMeasure}
        collapsedContent={<span className={css.peek}>{icon}</span>}
        panels={[
          {
            id: "tools",
            content: (
              <>
                {show.undo && (
                  <>
                    <span className={css.seated}>
                      <button
                        type="button"
                        className={css.round}
                        disabled={!canUndo}
                        onClick={onUndo}
                        aria-label="Undo"
                        {...tip.bindControl(
                          "Undo",
                          shortcuts ? "⌘Z" : undefined,
                        )}
                      >
                        <UndoIcon />
                      </button>
                    </span>
                    <span className={css.seated}>
                      <button
                        type="button"
                        className={css.round}
                        disabled={!canRedo}
                        onClick={onRedo}
                        aria-label="Redo"
                        {...tip.bindControl(
                          "Redo",
                          shortcuts ? "⇧⌘Z" : undefined,
                        )}
                      >
                        <RedoIcon />
                      </button>
                    </span>
                  </>
                )}

                {show.clear && (
                  <span className={css.seated}>
                    <button
                      type="button"
                      className={css.round}
                      data-tone="danger"
                      disabled={!hasStrokes}
                      onClick={onClear}
                      aria-label="Clear"
                      {...tip.bindControl("Clear all")}
                    >
                      <TrashIcon />
                    </button>
                  </span>
                )}

                {(show.undo || show.clear) && <span className={css.divider} />}

                {pens.map((pen) => (
                  <button
                    key={pen.id}
                    type="button"
                    className={css.tool}
                    data-active={tool.active === pen.id || undefined}
                    onClick={(e) => {
                      // Selecting is the first click. A second click on the
                      // tool you're already holding opens its settings, which
                      // keeps one tap between you and the tray at all times.
                      if (settings === "tool" && tool.active === pen.id) {
                        if (openTool && !closingTool) closeMenu();
                        else showMenu(e.currentTarget);
                        return;
                      }
                      if (openTool) closeMenu();
                      onSelect(pen.id);
                    }}
                    aria-label={pen.name}
                    aria-pressed={tool.active === pen.id}
                    aria-expanded={
                      settings === "tool" && tool.active === pen.id
                        ? openTool !== null
                        : undefined
                    }
                    {...tip.bind(pen.name, shortcuts ? pen.key : undefined)}
                  >
                    <ToolIcon
                      id={pen.id}
                      color={inkFor(pen.id)}
                      look={look}
                      badge={gauge && tool.active === pen.id ? size : undefined}
                    />
                  </button>
                ))}

                {eraser && (
                  <button
                    type="button"
                    className={css.tool}
                    data-active={isEraser || undefined}
                    onClick={() => onSelect("eraser")}
                    aria-label="Eraser"
                    aria-pressed={isEraser}
                    {...tip.bind("Eraser", shortcuts ? "E" : undefined)}
                  >
                    <ToolIcon id="eraser" color={tool.color} look={look} />
                  </button>
                )}

                {((show.size && settings === "bar") || show.color) && (
                  <span className={css.divider} />
                )}

                {/* Brush size, shown as a dot at its actual relative weight. */}
                {(show.size || show.opacity) && settings === "bar" && (
                  <span className={css.seated}>
                    {/* The eraser has no opacity to set, and the panel this
                        opens shows it one slider — so promising two is wrong,
                        in the label and to a screen reader alike. */}
                    <button
                      type="button"
                      className={css.round}
                      onClick={() => setMode("brush")}
                      aria-label={sizeLabel}
                      {...tip.bindControl(sizeLabel)}
                    >
                      <span
                        className={css.brushDot}
                        style={{
                          width: 6 + (size / maxSize) * 16,
                          height: 6 + (size / maxSize) * 16,
                          background: isEraser ? "#c9c7c2" : tool.color,
                          opacity: isEraser ? 1 : tool.opacity,
                        }}
                      />
                    </button>
                  </span>
                )}

                {show.color && (
                  <span className={css.seated}>
                    <button
                      type="button"
                      className={css.round}
                      onClick={() => setMode("ink")}
                      aria-label={`Ink colour — ${tool.color}`}
                      {...tip.bindControl("Colour")}
                    >
                      <span className={css.wheel}>
                        <span
                          className={css.wheelInk}
                          style={{ background: tool.color }}
                        />
                      </span>
                    </button>
                  </span>
                )}

                {show.minimize && <span className={css.divider} />}

                {show.minimize && (
                  <span className={css.seated}>
                    <button
                      type="button"
                      className={css.round}
                      onClick={onCollapse}
                      aria-label="Hide tools"
                      {...tip.bindControl("Hide tools")}
                    >
                      <CollapseIcon />
                    </button>
                  </span>
                )}
              </>
            ),
          },

          {
            id: "ink",
            content: (
              <div
                className={`${morph.centered} ${css.row} ${css.inkRow}`}
                data-open-end={!show.custom || undefined}
              >
                {back}
                <span className={css.divider} />
                <div className={css.swatches}>
                  {resolveSwatches(swatches, vertical).map((c) => (
                    <button
                      key={c}
                      type="button"
                      className={css.chip}
                      data-active={
                        tool.color.toLowerCase() === c.toLowerCase() ||
                        undefined
                      }
                      style={{ background: c }}
                      onClick={() => {
                        onChange({ color: c });
                        // Reaching for a colour means you want to draw with it.
                        if (isEraser) onSelect("pen");
                      }}
                      aria-label={c}
                      title={c}
                    >
                      {/* A tick reads as chosen at any swatch colour; a ring cut
                        into the swatch turns it into a donut and fights dark
                        colours. */}
                      <svg
                        className={css.tick}
                        viewBox="0 0 16 16"
                        fill="none"
                        stroke={isLight(c) ? "#111" : "#fff"}
                        strokeWidth="2.4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        aria-hidden="true"
                      >
                        <path d="M3.6 8.4 6.7 11.5 12.4 5.2" />
                      </svg>
                    </button>
                  ))}
                </div>
                {show.custom && (
                  <>
                    <span className={css.divider} />
                    <button
                      type="button"
                      className={css.custom}
                      onClick={() => setMode("spectrum")}
                      aria-label="Pick any colour"
                      {...tip.bindControl("Any colour")}
                    >
                      <span />
                    </button>
                  </>
                )}
              </div>
            ),
          },

          {
            id: "spectrum",
            content: (
              <div className={`${morph.centered} ${css.row}`}>
                <button
                  type="button"
                  className={css.round}
                  onClick={() => setMode("ink")}
                  aria-label="Back to swatches"
                  {...tip.bindControl("Back")}
                >
                  <BackIcon />
                </button>
                <span className={css.divider} />
                <span
                  className={css.preview}
                  style={{ background: tool.color }}
                  aria-hidden
                />
                {/* Not on a rail. Six characters and a field to hold them needs
                  more width than 66px has, and every way of cramming it in
                  looked cramped. The eyedropper covers picking an exact colour;
                  typing one is a job for the wide bar. */}
                {!vertical && (
                  <HexField
                    value={tool.color}
                    onChange={(color) => {
                      onChange({ color });
                      if (isEraser) onSelect("pen");
                    }}
                  />
                )}
                {canPick && (
                  <button
                    type="button"
                    className={css.round}
                    aria-label="Pick a colour from the screen"
                    {...tip.bindControl("Pick from screen")}
                    onClick={async () => {
                      const picked = await pickFromScreen();
                      if (!picked) return;
                      onChange({ color: picked });
                      if (isEraser) onSelect("pen");
                    }}
                  >
                    <DropperIcon />
                  </button>
                )}
              </div>
            ),
          },

          {
            id: "brush",
            content: (
              <div className={`${morph.centered} ${css.row} ${css.tail}`}>
                {back}
                {show.size && (
                  <>
                    <span className={css.divider} />
                    <BarSlider
                      vertical={vertical}
                      label="Size"
                      value={size}
                      min={1}
                      max={maxSize}
                      curve={2}
                      display={String(Math.round(size))}
                      color={isEraser ? "#c9c7c2" : tool.color}
                      onChange={(n) =>
                        onChange(isEraser ? { eraserSize: n } : { size: n })
                      }
                    />
                  </>
                )}
                {show.opacity && !isEraser && (
                  <>
                    <span className={css.divider} />
                    <BarSlider
                      vertical={vertical}
                      label="Opacity"
                      value={tool.opacity}
                      min={0.05}
                      max={1}
                      display={`${Math.round(tool.opacity * 100)}%`}
                      color={tool.color}
                      checker
                      onChange={(opacity) => onChange({ opacity })}
                    />
                  </>
                )}
              </div>
            ),
          },
        ]}
      />
      {tip.node}
      {settings === "tool" && openTool && (
        <ToolMenu
          anchor={openTool}
          size={menu.size}
          maxSize={menu.maxSize}
          opacity={menu.opacity}
          color={menu.color}
          showOpacity={menu.showOpacity}
          theme={theme}
          closing={closingTool}
          onSize={(n) => onChange(isEraser ? { eraserSize: n } : { size: n })}
          onOpacity={(opacity) => onChange({ opacity })}
          onClose={closeMenu}
        />
      )}
    </>
  );
}
